/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INTERFACES;

import javax.swing.JFrame;

/**
 *
 * @author Andrey
 */
public class Frmregistro extends javax.swing.JFrame {

    /**
     * Creates new form Frmregistro
     */
    public Frmregistro() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        Menubar = new javax.swing.JMenuBar();
        Mregistrar = new javax.swing.JMenu();
        Mvehiculos = new javax.swing.JMenuItem();
        Msalidas = new javax.swing.JMenuItem();
        Mllegadas = new javax.swing.JMenuItem();
        Mconfiguracion = new javax.swing.JMenu();
        Mconfigbd = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 250));

        Mregistrar.setText("Registrar");

        Mvehiculos.setText("Vehículos");
        Mvehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MvehiculosActionPerformed(evt);
            }
        });
        Mregistrar.add(Mvehiculos);

        Msalidas.setText("Salidas");
        Mregistrar.add(Msalidas);

        Mllegadas.setText("LLegadas");
        Mllegadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MllegadasActionPerformed(evt);
            }
        });
        Mregistrar.add(Mllegadas);

        Menubar.add(Mregistrar);

        Mconfiguracion.setText("Configuración");
        Mconfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MconfiguracionActionPerformed(evt);
            }
        });

        Mconfigbd.setText("Config.BD");
        Mconfigbd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MconfigbdActionPerformed(evt);
            }
        });
        Mconfiguracion.add(Mconfigbd);

        Menubar.add(Mconfiguracion);

        setJMenuBar(Menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MllegadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MllegadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MllegadasActionPerformed

    private void MvehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MvehiculosActionPerformed
        Vista.vistavehiculos c = new Vista.vistavehiculos();
        escritorio.add(c);
        c.show();
    }//GEN-LAST:event_MvehiculosActionPerformed

    private void MconfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MconfiguracionActionPerformed

    }//GEN-LAST:event_MconfiguracionActionPerformed

    private void MconfigbdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MconfigbdActionPerformed
        UIConfiguracion config = new UIConfiguracion();
        this.dispose();
        config.setVisible(true);
        while (config.isVisible()) {
            this.dispose();
        }
        this.setVisible(true);
    }//GEN-LAST:event_MconfigbdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frmregistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frmregistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frmregistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frmregistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frmregistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Mconfigbd;
    private javax.swing.JMenu Mconfiguracion;
    private javax.swing.JMenuBar Menubar;
    private javax.swing.JMenuItem Mllegadas;
    private javax.swing.JMenu Mregistrar;
    private javax.swing.JMenuItem Msalidas;
    private javax.swing.JMenuItem Mvehiculos;
    private javax.swing.JDesktopPane escritorio;
    // End of variables declaration//GEN-END:variables
}
